version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_database_user
      MYSQL_PASSWORD: your_database_password # for test!!
      MYSQL_ROOT_PASSWORD: your_root_password
    networks:
      - mynetwork

  webapp:
    container_name: web_app
    build: .
    command: sh -c "while ! nc -z db 3306; do sleep 1; done && python manage.py migrate && test -d static || mkdir static && python manage.py collectstatic --noinput && gunicorn -w 1 -k uvicorn.workers.UvicornWorker 'gTeamProject.asgi:application' --bind=0.0.0.0:8000 --reload"
    hostname: webapp
    ports:
      - 8000:8000
    depends_on:
      - db
      - celery
      - rabbit
      - redis
    networks:
      - mynetwork
    volumes:
      - ./:/usr/src/app

  celery:
    container_name: celery_worker
    build: .
    command: sh -c "celery -A celery_worker worker --loglevel=info"
    depends_on:
      - rabbit
      - redis
    networks:
      - mynetwork
    volumes:
      - ./celery_worker:/usr/src/app/celery_worker

  rabbit:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbit
    environment:
      - RABBITMQ_USER=guest
      - RABBITMQ_PASSWORD=guest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis:latest
    hostname: redis
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
