# Generated by Django 4.2.3 on 2023-07-12 13:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="poll",
            old_name="user_id",
            new_name="user",
        ),
    ]
